[project]
name = "lnbits-zapgoals"
version = "0.1.4"
requires-python = ">=3.10,<3.13"
description = "LNbits extension for shareable Lightning funding goals."
authors = [{ name = "bitkarrot" }]
urls = { Homepage = "https://github.com/bitkarrot/zapgoals", Repository = "https://github.com/bitkarrot/zapgoals" }
dependencies = ["lnbits>=1.5.0"]

[dependency-groups]
dev = [
    "black",
    "mypy",
    "pre-commit",
    "pytest",
    "pytest-asyncio",
    "ruff",
]

[tool.poetry]
package-mode = false

[tool.mypy]
plugins = ["pydantic.mypy"]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[[tool.mypy.overrides]]
module = [
    "lnbits.*",
    "lnurl.*",
    "loguru.*",
    "pynostr.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
log_cli = false
testpaths = ["tests"]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["F", "E", "W", "I", "A", "C", "N", "UP", "RUF", "B"]
ignore = ["C901"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["validator", "root_validator"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]
